-- AlterTable
ALTER TABLE "bill" ALTER COLUMN "finished_at" DROP NOT NULL,
ALTER COLUMN "cancelled_at" DROP NOT NULL,
ALTER COLUMN "delay" DROP NOT NULL,
ALTER COLUMN "due_date" DROP NOT NULL,
ALTER COLUMN "importance" DROP NOT NULL,
ALTER COLUMN "net_value" DROP NOT NULL,
ALTER COLUMN "pdf_url" DROP NOT NULL,
ALTER COLUMN "receipt" DROP NOT NULL;
